name=ModbusRTU-pico
version=1.0.2
author=Jimes Yang
maintainer=Jimes Yang <admin@sndnvaps>
sentence=ModbusRTU slave for Raspberry pico, RP2040/RP2350
paragraph=
category=Signal Input/Output
url=https://github.com/sndnvaps/modbus-pico
includes=ModbusRTU_PICO.h
architectures=rp2040,rp2350
depends=



