name=ModbusRTU-pico
version=4.3.2
author=Jimes Yang
maintainer=Jimes Yang <admin@sndnvaps>
sentence=Modbus Library for Arduino. ModbusRTU, ModbusTCP and ModbusTCP Security(support Raspberry picoW, pico2W,rp2040,rp2350...)
paragraph=Most complete Modbus protocol implementation for Arduino. The Modbus is a master-slave protocol used in industrial automation and also can be used in other areas, such as home automation.
category=Communication
url=https://github.com/sndnvaps/modbus-pico
includes=ModbusRTU_PICO.h,ModbusIP_PICO.h,ModbusEthernet.h,ModbusLWIP_Ethernet.h,ModbusTLS.h
architectures=rp2040
depends=



